CREATE DATABASE pg_start_dev;
CREATE USER dev_user WITH PASSWORD '123test';
GRANT ALL PRIVILEGES ON DATABASE pg_start_dev to dev_user;
ALTER USER dev_user WITH SUPERUSER;
ALTER ROLE dev_user CREATEROLE CREATEDB;