package utils

import (
	"crypto/rand"
	"encoding/base64"
)

const TokenBytes = 32

// Generate token of a predetermined byte size.
func GenerateToken() (string, error) {
	return generateEncodedString(TokenBytes)
}

// Generate n random bytes.
func GenerateRandomBytes(n int) ([]byte, error) {
	b := make([]byte, n)
	_, err := rand.Read(b)
	if err != nil {
		return nil, err
	}
	return b, nil
}

// Generate a byte slice of size nBytes and then
// return a string that is the base64 URL encoded version
// of that byte slice
func generateEncodedString(nBytes int) (string, error) {
	b, err := GenerateRandomBytes(nBytes)
	if err != nil {
		return "", err
	}
	return base64.URLEncoding.EncodeToString(b), nil
}

// Returns the number of bytes used in any string
// generated by the String or GenerateToken function
func NumberOfBytes(base64String string) (int, error) {
	b, err := base64.URLEncoding.DecodeString(base64String)
	if err != nil {
		return -1, err
	}
	return len(b), nil
}
